# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# For Next.js on Alpine, this avoids some glibc issues
RUN apk add --no-cache libc6-compat

ENV NODE_ENV=development

EXPOSE 3000

# Install dependencies & run dev server.
# Because /app is a volume, node_modules will live on your host.
CMD ["sh", "-c", "npm install && npm run dev -- -H 0.0.0.0 -p 3000"]
